version: "3.9"

x-aws-env: &aws-credentials
  AWS_ACCESS_KEY_ID: ASIAVRUVPMCXU5BU54FM
  AWS_SECRET_ACCESS_KEY: fe5L/aCFqEA+qik2SKt1WRAtW7moUaNJvVTHe26+
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEM3//////////wEaCXVzLXdlc3QtMiJHMEUCIC+Wbfi5s9jfk1QdE+CRdR6z/wHPvmC2mfI4aICt4zxBAiEA+KWFBzaxhzvR52TeWY0tocr/JhhIkhF9uUixGdddEjkqnAIIZhAAGgwzODE0OTE4MzA5NTkiDARgAJwHzjNr/r5tNSr5AQkSv1XgbpV6TaYXQLMBAFNZmst8PAltkUa4rF74Onna67+XhxOWP8HDqtBDDI61ieYCfZ6jxgkE4JDVbfH+MgB0do2EFD1cB0LZqJu9NJvV3oJC+SeeCCJB9S52lp3JBijPwR+JRa+17IdgMakGUAtBDHl1+gzdAKorYHuxFoE6iJn4IV712Fj8ASLkV3eZTW0cA7JglFxiRGRgUhcZBkujMsZu4knvhMeub6YUXp9frtVb/sB0V1ZWIP9irXi1jw0XNY/3kO44q8SFrqzl+JM0YSkuMdOFnJrJ1CMXYlSRhFHe0A5sLMX4Nukjr4aSL8hCJ/6MvY38uTD81O65BjqdAcC8hbwOL7N8CtzkGJ4IB37X098kqOQWgegnFI5TlJUqoF9T3S+i1wQoWvsEJmt8Fs/To5HV4qBh/MQ9GdL6Y6Kb4/+9qz9KdE+vI74i1Ac9b24S/HDN0HmpYvApzok4O36tXB+9jBv+CCUiLW44vhEbSGI7STqy112v4Qw7xiBJFFNWx7IVlOv+3yjnnhMPPHow8Lf0Gm7J1rA223I=
  AWS_REGION: us-east-1
  S3_BUCKET: ciencia-de-datos
  STAGE: dev

services:
  microservice1:
    build:
      context: ./service
    environment:
      <<: *aws-credentials
      DYNAMODB_TABLES: Horarios
    container_name: dynamodb_microservice1
    auto_remove: true

  microservice2:
    build:
      context: ./service
    environment:
      <<: *aws-credentials
      DYNAMODB_TABLES: Ordenes
    container_name: dynamodb_microservice2
    auto_remove: true

  microservice3:
    build:
      context: ./service
    environment:
      <<: *aws-credentials
      DYNAMODB_TABLES: Peliculas
    container_name: dynamodb_microservice3
    auto_remove: true

  microservice4:
    build:
      context: ./service
    environment:
      <<: *aws-credentials
      DYNAMODB_TABLES: Productos
    container_name: dynamodb_microservice4
    auto_remove: true

  microservice5:
    build:
      context: ./service
    environment:
      <<: *aws-credentials
      DYNAMODB_TABLES: Reservas,Usuarios
    container_name: dynamodb_microservice5
    auto_remove: true
